name: Build AppImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]         

jobs:

  build-ubuntu-x64:
    name: Build AppImage ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        env: # Or as an environment variable
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: List keys5
        run: gpg -K

      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libogg-dev libvorbis-dev libmpg123-dev &&
          sudo apt-get install -qq -y zlib1g-dev libglew-dev libmpg123-dev libmpg123-0 libcurl4-nss-dev
          
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
           format: "YYYYMMDD"

      - name: Show current date
        run: |
          echo "${{ steps.date.outputs.time }}"         
      - name: Run Build
        run: |
            cd ${{github.workspace}}
            sh Linux/AppImage/build-appimage.sh
            find . -name ironwail-x86_64.AppImage -exec mv -f {} . \;
            mv -f ${{github.workspace}}/ironwail-x86_64.AppImage ironwail-${{ steps.date.outputs.time }}-0.8.0-x86_64.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ironwail-${{ steps.date.outputs.time }}-0.8.0-x86_64.AppImage
          path: ironwail-${{ steps.date.outputs.time }}-0.8.0-x86_64.AppImage
